"""Agentic hexagonal architecture contracts for Spakky Framework."""

from spakky.core.application.plugin import Plugin

from spakky.agent.error import (
    AbstractSpakkyAgentError,
    AgentBootstrapError,
    AgentDefinitionError,
    AgentModelConfigurationError,
    AgentPersistenceConfigurationError,
)
from spakky.agent.context import (
    ContextDigest,
    ContextFreshness,
    ContextManifest,
    ContextManifestEntry,
    ContextPack,
    ContextPackRole,
    ContextSensitivity,
    ContextTokenBudget,
)
from spakky.agent.evidence import AgentEvidence, AgentEvidenceKind
from spakky.agent.execution import (
    Agent,
    AgentExecutionLimits,
    AgentExecutionSpec,
    AgentSignalKind,
    RecoveryStrategy,
    StreamingExposureMode,
)
from spakky.agent.interfaces.repository import (
    IAgentEvidenceRepository,
    IAgentSignalRepository,
    IAgentStateRepository,
)
from spakky.agent.interfaces.model import (
    IAgentModel,
    JsonSchemaConstraint,
    ModelError,
    ModelMessage,
    ModelMessageRole,
    ModelRequest,
    ModelResponse,
    ModelStreamEvent,
    ModelStreamEventKind,
    ModelToolCall,
    ModelToolChoice,
    ModelToolSpec,
    ModelUsage,
    SamplingOptions,
    StreamingOptions,
    StructuredOutputSpec,
    ToolCallingSpec,
)
from spakky.agent.signal import AgentSignal, ApprovalDecision
from spakky.agent.state import (
    AgentState,
    AgentStateReason,
    AgentStateTransition,
    AgentStatus,
)
from spakky.agent.tooling import (
    AgentToolCatalog,
    AgentToolDefinition,
    AgentToolDescriptor,
    AgentToolIdentity,
    AgentToolMetadata,
    AgentToolSchemaHandle,
    DataAccess,
    EvidenceCapture,
    Externality,
    Idempotency,
    ResultBudget,
    TimeoutPolicy,
    ToolApprovalRequirement,
    ToolEffects,
    ToolPermission,
    agent_tool,
    discover_agent_tools,
)
from spakky.agent.types import JsonObject, JsonPrimitive, JsonValue
from spakky.agent.yield_ import (
    AgentYield,
    AgentYieldKind,
    AgentYieldPayload,
    Approval,
    Cancel,
    Error,
    Evidence,
    Final,
    Message,
    Progress,
    TextDelta,
    Token,
    Tool,
)

PLUGIN_NAME = Plugin(name="spakky-agent")
"""Plugin identifier for the Spakky Agent package."""

__all__ = [
    "IAgentModel",
    "IAgentEvidenceRepository",
    "IAgentSignalRepository",
    "IAgentStateRepository",
    "AbstractSpakkyAgentError",
    "Agent",
    "AgentBootstrapError",
    "AgentDefinitionError",
    "AgentEvidence",
    "AgentEvidenceKind",
    "AgentExecutionLimits",
    "AgentExecutionSpec",
    "AgentModelConfigurationError",
    "AgentPersistenceConfigurationError",
    "AgentSignal",
    "AgentSignalKind",
    "AgentToolCatalog",
    "AgentToolDefinition",
    "AgentToolDescriptor",
    "AgentToolIdentity",
    "AgentToolMetadata",
    "AgentToolSchemaHandle",
    "AgentStateReason",
    "AgentStateTransition",
    "AgentState",
    "AgentStatus",
    "AgentYield",
    "AgentYieldKind",
    "AgentYieldPayload",
    "Approval",
    "ApprovalDecision",
    "Cancel",
    "ContextDigest",
    "ContextFreshness",
    "ContextManifest",
    "ContextManifestEntry",
    "ContextPack",
    "ContextPackRole",
    "ContextSensitivity",
    "ContextTokenBudget",
    "Error",
    "DataAccess",
    "EvidenceCapture",
    "Evidence",
    "Externality",
    "Final",
    "Idempotency",
    "JsonObject",
    "JsonPrimitive",
    "JsonSchemaConstraint",
    "JsonValue",
    "Message",
    "ModelError",
    "ModelMessage",
    "ModelMessageRole",
    "ModelRequest",
    "ModelResponse",
    "ModelStreamEvent",
    "ModelStreamEventKind",
    "ModelToolCall",
    "ModelToolChoice",
    "ModelToolSpec",
    "ModelUsage",
    "PLUGIN_NAME",
    "Progress",
    "RecoveryStrategy",
    "ResultBudget",
    "SamplingOptions",
    "StreamingOptions",
    "StreamingExposureMode",
    "StructuredOutputSpec",
    "TextDelta",
    "Token",
    "Tool",
    "TimeoutPolicy",
    "ToolApprovalRequirement",
    "ToolCallingSpec",
    "ToolEffects",
    "ToolPermission",
    "agent_tool",
    "discover_agent_tools",
]
