"""Defaults for the spakky-llm plugin."""

SPAKKY_LLM_CONFIG_ENV_PREFIX = "SPAKKY_LLM__"

DEFAULT_LLM_PROFILE = "default"
DEFAULT_LLM_PROVIDER = "vllm"
DEFAULT_LLM_MODEL = "default"
DEFAULT_LLM_BASE_URL = "http://127.0.0.1:8000/v1"
DEFAULT_LLM_API_KEY = "EMPTY"
DEFAULT_LLM_REQUEST_TIMEOUT_SECONDS = 30.0
DEFAULT_LLM_STREAM_TIMEOUT_SECONDS = 300.0
DEFAULT_LLM_MAX_RETRIES = 0
DEFAULT_ANTHROPIC_MAX_TOKENS = 4096

OFFICIAL_OPENAI_BASE_URL = "https://api.openai.com/v1"
OFFICIAL_ANTHROPIC_BASE_URL = "https://api.anthropic.com"
OFFICIAL_GOOGLE_BASE_URL = "https://generativelanguage.googleapis.com/"
