#!/usr/bin/env python3
"""Extract release information for a specific package.

This script extracts version and tag information from the release info string
generated by bump_packages.py.

Usage:
    python scripts/extract_release_info.py <package> <released_info>

Example:
    python scripts/extract_release_info.py spakky "spakky:3.1.2:spakky-v3.1.2;spakky-fastapi:3.1.2:spakky-fastapi-v3.1.2"

Environment:
    GITHUB_OUTPUT: Path to GitHub Actions output file (optional)
"""

from __future__ import annotations

import os
import sys


def write_github_output(key: str, value: str) -> None:
    """Write output to GitHub Actions."""
    github_output = os.environ.get("GITHUB_OUTPUT")
    if github_output:
        with open(github_output, "a") as f:
            f.write(f"{key}={value}\n")


def extract_release_info(package: str, released_info: str) -> tuple[str, str] | None:
    """Extract version and tag for a specific package.

    Args:
        package: The package name to look for.
        released_info: Semicolon-separated string of "package:version:tag" entries.

    Returns:
        Tuple of (version, tag) if found, None otherwise.
    """
    if not released_info:
        return None

    for entry in released_info.split(";"):
        if not entry:
            continue
        parts = entry.split(":")
        if len(parts) >= 3 and parts[0] == package:
            return parts[1], parts[2]

    return None


def main() -> int:
    """Main entry point."""
    if len(sys.argv) < 3:
        print(
            "Usage: python extract_release_info.py <package> <released_info>",
            file=sys.stderr,
        )
        return 1

    package = sys.argv[1]
    released_info = sys.argv[2]

    result = extract_release_info(package, released_info)

    if result is None:
        print(f"❌ Package '{package}' not found in release info", file=sys.stderr)
        return 1

    version, tag = result
    print(f"📦 {package} v{version} will be published")

    write_github_output("version", version)
    write_github_output("tag", tag)

    # Also print for local debugging
    print(f"version={version}")
    print(f"tag={tag}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
