"""Provider-neutral authentication and authorization package root."""

from spakky.auth.constants import (
    AUTH_CONTEXT_CONTEXT_KEY,
    AUTH_CONTEXT_SNAPSHOT_HEADER_KEY,
    AUTH_CONTEXT_SNAPSHOT_METADATA_KEY,
    AUTH_CONTEXT_SNAPSHOT_SCHEMA_VERSION,
    DEFAULT_AUTH_CLOCK_SKEW_SECONDS,
)
from spakky.auth.capability import AuthCapability
from spakky.auth.contribution import (
    AUTH_CONTRIBUTION_ENTRY_POINT_GROUP,
    AuthContributionProviderId,
    AuthProviderContribution,
)
from spakky.auth.context import (
    AuthClaim,
    AuthClaimValue,
    AuthContext,
    AuthSubject,
    require_auth_context,
    store_auth_context,
)
from spakky.auth.credential import (
    CredentialCarrier,
    CredentialCarrierKind,
    CredentialCarrierLocation,
)
from spakky.auth.decision import (
    EXPIRED_SNAPSHOT_DECISION,
    INVALID_SNAPSHOT_DECISION,
    MISSING_SNAPSHOT_DECISION,
    VERIFICATION_PROVIDER_UNAVAILABLE_DECISION,
    AuthorizationDecision,
    AuthorizationDecisionState,
    AuthorizationReasonCode,
)
from spakky.auth.error import (
    AbstractSpakkyAuthError,
    AuthContextError,
    AuthContextNotFoundError,
    AuthContextSnapshotError,
    AuthVerificationProviderUnavailableError,
    AuthenticationError,
    AuthorizationError,
    CredentialCarrierError,
    ExpiredAuthContextSnapshotError,
    InvalidAuthContextSnapshotError,
    InvalidAuthContextValueError,
    MissingAuthContextSnapshotError,
)
from spakky.auth.invocation import (
    AuthActionRef,
    AuthBoundaryRef,
    AuthDynamicRef,
    AuthDynamicRefExpression,
    AuthDynamicRefKind,
    AuthInvocation,
    AuthInvocationAttribute,
    AuthInvocationAttributeName,
    AuthInvocationAttributeValue,
    AuthInvocationOperationRef,
    AuthPermissionRef,
    AuthRelationRef,
    AuthResolvedRef,
    AuthResourceRef,
    AuthRoleRef,
    AuthScopeRef,
    AuthTenantRef,
    ResolvedAuthReference,
)
from spakky.auth.ports import (
    AuthPasswordHash,
    AuthPasswordPlaintext,
    AuthorizationRequest,
    IAuthContextSnapshotSigner,
    IAuthContextSnapshotVerifier,
    IAuthInvocationResolver,
    IAuthenticationProvider,
    IAuthorizationPolicyEvaluator,
    IPasswordHasher,
    IPasswordVerifier,
    IPermissionChecker,
    IRelationChecker,
    IRoleChecker,
    IScopeChecker,
    PermissionCheckRequest,
    RelationCheckRequest,
    RoleCheckRequest,
    ScopeCheckRequest,
    SnapshotSignRequest,
)
from spakky.auth.snapshot import AuthContextSnapshot, AuthContextSnapshotSignature
from spakky.core.application.plugin import Plugin

PLUGIN_NAME = Plugin(name="spakky-auth")
"""Plugin identifier for the Spakky Auth package."""

__all__ = [
    "AUTH_CONTEXT_CONTEXT_KEY",
    "AUTH_CONTEXT_SNAPSHOT_HEADER_KEY",
    "AUTH_CONTEXT_SNAPSHOT_METADATA_KEY",
    "AUTH_CONTEXT_SNAPSHOT_SCHEMA_VERSION",
    "AUTH_CONTRIBUTION_ENTRY_POINT_GROUP",
    "DEFAULT_AUTH_CLOCK_SKEW_SECONDS",
    "EXPIRED_SNAPSHOT_DECISION",
    "INVALID_SNAPSHOT_DECISION",
    "MISSING_SNAPSHOT_DECISION",
    "PLUGIN_NAME",
    "VERIFICATION_PROVIDER_UNAVAILABLE_DECISION",
    "AbstractSpakkyAuthError",
    "AuthActionRef",
    "AuthClaim",
    "AuthClaimValue",
    "AuthBoundaryRef",
    "AuthCapability",
    "AuthContext",
    "AuthContextError",
    "AuthContextNotFoundError",
    "AuthContextSnapshot",
    "AuthContextSnapshotError",
    "AuthContextSnapshotSignature",
    "AuthContributionProviderId",
    "AuthDynamicRef",
    "AuthDynamicRefExpression",
    "AuthDynamicRefKind",
    "AuthInvocation",
    "AuthInvocationAttribute",
    "AuthInvocationAttributeName",
    "AuthInvocationAttributeValue",
    "AuthInvocationOperationRef",
    "AuthPasswordHash",
    "AuthPasswordPlaintext",
    "AuthPermissionRef",
    "AuthProviderContribution",
    "AuthRelationRef",
    "AuthResolvedRef",
    "AuthResourceRef",
    "AuthRoleRef",
    "AuthScopeRef",
    "AuthSubject",
    "AuthTenantRef",
    "AuthVerificationProviderUnavailableError",
    "AuthenticationError",
    "AuthorizationDecision",
    "AuthorizationDecisionState",
    "AuthorizationError",
    "AuthorizationRequest",
    "AuthorizationReasonCode",
    "CredentialCarrier",
    "CredentialCarrierError",
    "CredentialCarrierKind",
    "CredentialCarrierLocation",
    "ExpiredAuthContextSnapshotError",
    "IAuthContextSnapshotSigner",
    "IAuthContextSnapshotVerifier",
    "IAuthInvocationResolver",
    "IAuthenticationProvider",
    "IAuthorizationPolicyEvaluator",
    "IPasswordHasher",
    "IPasswordVerifier",
    "IPermissionChecker",
    "IRelationChecker",
    "IRoleChecker",
    "IScopeChecker",
    "InvalidAuthContextSnapshotError",
    "InvalidAuthContextValueError",
    "MissingAuthContextSnapshotError",
    "PermissionCheckRequest",
    "require_auth_context",
    "RelationCheckRequest",
    "ResolvedAuthReference",
    "RoleCheckRequest",
    "ScopeCheckRequest",
    "SnapshotSignRequest",
    "store_auth_context",
]
